import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const trophies = [
  // Score-Based Trophies (5)
  {
    key: 'first_steps',
    name: 'First Steps',
    description: 'Score 50,000 total points',
    category: 'score',
    tier: 'bronze',
    icon: '🥉',
    requirement: 50000,
  },
  {
    key: 'rising_star',
    name: 'Rising Star',
    description: 'Score 250,000 total points',
    category: 'score',
    tier: 'silver',
    icon: '🥈',
    requirement: 250000,
  },
  {
    key: 'card_master',
    name: 'Card Master',
    description: 'Score 1,000,000 total points',
    category: 'score',
    tier: 'gold',
    icon: '🥇',
    requirement: 1000000,
  },
  {
    key: 'legend',
    name: 'Legend',
    description: 'Score 5,000,000 total points',
    category: 'score',
    tier: 'diamond',
    icon: '💎',
    requirement: 5000000,
  },
  {
    key: 'hall_of_fame',
    name: 'Hall of Fame',
    description: 'Score 10,000,000 total points',
    category: 'score',
    tier: 'diamond',
    icon: '👑',
    requirement: 10000000,
  },

  // Game-Based Trophies (5)
  {
    key: 'beginner',
    name: 'Beginner',
    description: 'Play 10 games',
    category: 'games',
    tier: 'bronze',
    icon: '🎮',
    requirement: 10,
  },
  {
    key: 'regular',
    name: 'Regular',
    description: 'Play 50 games',
    category: 'games',
    tier: 'silver',
    icon: '🎮',
    requirement: 50,
  },
  {
    key: 'veteran',
    name: 'Veteran',
    description: 'Play 100 games',
    category: 'games',
    tier: 'gold',
    icon: '🎮',
    requirement: 100,
  },
  {
    key: 'dedicated',
    name: 'Dedicated',
    description: 'Play 500 games',
    category: 'games',
    tier: 'diamond',
    icon: '🎮',
    requirement: 500,
  },
  {
    key: 'addicted',
    name: 'Addicted',
    description: 'Play 1,000 games',
    category: 'games',
    tier: 'diamond',
    icon: '🎮',
    requirement: 1000,
  },

  // Win-Based Trophies (5)
  {
    key: 'first_victory',
    name: 'First Victory',
    description: 'Win your first game',
    category: 'wins',
    tier: 'bronze',
    icon: '🏆',
    requirement: 1,
  },
  {
    key: 'winner',
    name: 'Winner',
    description: 'Win 10 games',
    category: 'wins',
    tier: 'silver',
    icon: '🏆',
    requirement: 10,
  },
  {
    key: 'champion',
    name: 'Champion',
    description: 'Win 50 games',
    category: 'wins',
    tier: 'gold',
    icon: '🏆',
    requirement: 50,
  },
  {
    key: 'unbeatable',
    name: 'Unbeatable',
    description: 'Win 100 games',
    category: 'wins',
    tier: 'diamond',
    icon: '🏆',
    requirement: 100,
  },
  {
    key: 'dominator',
    name: 'Dominator',
    description: 'Win 250 games',
    category: 'wins',
    tier: 'diamond',
    icon: '🏆',
    requirement: 250,
  },

  // Streak Trophies (4)
  {
    key: 'hot_streak',
    name: 'Hot Streak',
    description: 'Guess 3 cards correctly in a row',
    category: 'streak',
    tier: 'silver',
    icon: '🔥',
    requirement: 3,
  },
  {
    key: 'on_fire',
    name: 'On Fire',
    description: 'Guess 5 cards correctly in a row',
    category: 'streak',
    tier: 'gold',
    icon: '🔥',
    requirement: 5,
  },
  {
    key: 'unstoppable',
    name: 'Unstoppable',
    description: 'Guess 10 cards correctly in a row',
    category: 'streak',
    tier: 'diamond',
    icon: '🔥',
    requirement: 10,
  },
  {
    key: 'legendary_streak',
    name: 'Legendary Streak',
    description: 'Guess 15 cards correctly in a row',
    category: 'streak',
    tier: 'diamond',
    icon: '🔥',
    requirement: 15,
  },

  // Card-Based Trophies (5)
  {
    key: 'quick_guesser',
    name: 'Quick Guesser',
    description: 'Guess 100 cards correctly',
    category: 'cards',
    tier: 'bronze',
    icon: '🎴',
    requirement: 100,
  },
  {
    key: 'card_expert',
    name: 'Card Expert',
    description: 'Guess 500 cards correctly',
    category: 'cards',
    tier: 'silver',
    icon: '🎴',
    requirement: 500,
  },
  {
    key: 'card_genius',
    name: 'Card Genius',
    description: 'Guess 1,000 cards correctly',
    category: 'cards',
    tier: 'gold',
    icon: '🎴',
    requirement: 1000,
  },
  {
    key: 'pokedex_complete',
    name: 'Pokédex Complete',
    description: 'Guess 5,000 cards correctly',
    category: 'cards',
    tier: 'diamond',
    icon: '🎴',
    requirement: 5000,
  },
  {
    key: 'master_collector',
    name: 'Master Collector',
    description: 'Guess 10,000 cards correctly',
    category: 'cards',
    tier: 'diamond',
    icon: '🎴',
    requirement: 10000,
  },

  // Special Trophies (10)
  {
    key: 'perfect_round',
    name: 'Perfect Round',
    description: 'Score 25,000+ points in a single round',
    category: 'special',
    tier: 'special',
    icon: '⭐',
    requirement: 25000,
  },
  {
    key: 'perfectionist',
    name: 'Perfectionist',
    description: 'Complete a game with 100% accuracy',
    category: 'special',
    tier: 'special',
    icon: '✨',
    requirement: 100,
  },
  {
    key: 'flawless_victory',
    name: 'Flawless Victory',
    description: 'Win a 10+ round game with 100% accuracy',
    category: 'special',
    tier: 'special',
    icon: '✨',
    requirement: 10,
  },
  {
    key: 'night_owl',
    name: 'Night Owl',
    description: 'Play a game between midnight and 4 AM',
    category: 'special',
    tier: 'fun',
    icon: '🦉',
    requirement: 1,
  },
  {
    key: 'early_bird',
    name: 'Early Bird',
    description: 'Play a game between 5 AM and 7 AM',
    category: 'special',
    tier: 'fun',
    icon: '🐦',
    requirement: 1,
  },
  {
    key: 'weekend_warrior',
    name: 'Weekend Warrior',
    description: 'Play 20 games on a weekend',
    category: 'special',
    tier: 'fun',
    icon: '🎉',
    requirement: 20,
  },
  {
    key: 'first_share',
    name: 'First Share',
    description: 'Share your score for the first time',
    category: 'social',
    tier: 'bronze',
    icon: '📤',
    requirement: 1,
  },
  {
    key: 'social_butterfly',
    name: 'Social Butterfly',
    description: 'Share your score 10 times',
    category: 'social',
    tier: 'silver',
    icon: '🦋',
    requirement: 10,
  },
  {
    key: 'influencer',
    name: 'Influencer',
    description: 'Share your score 50 times',
    category: 'social',
    tier: 'gold',
    icon: '📱',
    requirement: 50,
  },

  // Leaderboard Trophies (5)
  {
    key: 'challenger',
    name: 'Challenger',
    description: 'Beat an existing #1 player to take their spot',
    category: 'leaderboard',
    tier: 'diamond',
    icon: '⚔️',
    requirement: 1,
  },
  {
    key: 'top_player',
    name: 'Top Player',
    description: 'Reach #1 on any game mode leaderboard',
    category: 'leaderboard',
    tier: 'gold',
    icon: '🥇',
    requirement: 1,
  },
  {
    key: 'podium_finish',
    name: 'Podium Finish',
    description: 'Reach top 3 on any game mode leaderboard',
    category: 'leaderboard',
    tier: 'silver',
    icon: '🥈',
    requirement: 3,
  },
  {
    key: 'top_10',
    name: 'Top 10',
    description: 'Reach top 10 on any game mode leaderboard',
    category: 'leaderboard',
    tier: 'bronze',
    icon: '🥉',
    requirement: 10,
  },
  {
    key: 'multi_mode_master',
    name: 'Multi-Mode Master',
    description: 'Reach top 10 in 3 different game modes',
    category: 'leaderboard',
    tier: 'gold',
    icon: '🎯',
    requirement: 3,
  },

  // Personal Best Trophies (4)
  {
    key: 'self_improvement',
    name: 'Self Improvement',
    description: 'Beat your own high score on any game mode',
    category: 'personal_best',
    tier: 'bronze',
    icon: '📈',
    requirement: 1,
  },
  {
    key: 'consistency',
    name: 'Consistency',
    description: 'Beat your own high score 5 times',
    category: 'personal_best',
    tier: 'silver',
    icon: '📈',
    requirement: 5,
  },
  {
    key: 'always_improving',
    name: 'Always Improving',
    description: 'Beat your own high score 10 times',
    category: 'personal_best',
    tier: 'gold',
    icon: '📈',
    requirement: 10,
  },
  {
    key: 'unstoppable_growth',
    name: 'Unstoppable Growth',
    description: 'Beat your own high score 25 times',
    category: 'personal_best',
    tier: 'diamond',
    icon: '📈',
    requirement: 25,
  },

  // Rarity Trophies (9)
  {
    key: 'common_collector',
    name: 'Common Collector',
    description: 'Correctly guess 5 common cards',
    category: 'rarity',
    tier: 'bronze',
    icon: '⚪',
    requirement: 5,
  },
  {
    key: 'uncommon_collector',
    name: 'Uncommon Collector',
    description: 'Correctly guess 10 uncommon cards',
    category: 'rarity',
    tier: 'bronze',
    icon: '🟢',
    requirement: 10,
  },
  {
    key: 'rare_hunter',
    name: 'Rare Hunter',
    description: 'Correctly guess 20 rare cards',
    category: 'rarity',
    tier: 'silver',
    icon: '💎',
    requirement: 20,
  },
  {
    key: 'double_rare_hunter',
    name: 'Double Rare Hunter',
    description: 'Correctly guess 30 double rare cards',
    category: 'rarity',
    tier: 'silver',
    icon: '✨',
    requirement: 30,
  },
  {
    key: 'ultra_rare_collector',
    name: 'Ultra Rare Collector',
    description: 'Correctly guess 50 ultra rare cards',
    category: 'rarity',
    tier: 'gold',
    icon: '🌟',
    requirement: 50,
  },
  {
    key: 'illustration_admirer',
    name: 'Illustration Admirer',
    description: 'Correctly guess 60 illustration rare cards',
    category: 'rarity',
    tier: 'gold',
    icon: '🖼️',
    requirement: 60,
  },
  {
    key: 'secret_seeker',
    name: 'Secret Seeker',
    description: 'Correctly guess 75 secret rare cards',
    category: 'rarity',
    tier: 'diamond',
    icon: '💎',
    requirement: 75,
  },
  {
    key: 'special_investigator',
    name: 'Special Investigator',
    description: 'Correctly guess 80 special illustration rare cards',
    category: 'rarity',
    tier: 'diamond',
    icon: '🔍',
    requirement: 80,
  },
  {
    key: 'hyper_hunter',
    name: 'Hyper Hunter',
    description: 'Correctly guess 100 hyper rare cards',
    category: 'rarity',
    tier: 'diamond',
    icon: '🌈',
    requirement: 100,
  },
  {
    key: 'rarity_master',
    name: 'Rarity Master',
    description: 'Guess at least 1 card from 8 different rarities',
    category: 'rarity',
    tier: 'special',
    icon: '👑',
    requirement: 8,
  },

  // Set Trophies (4)
  {
    key: 'set_explorer',
    name: 'Set Explorer',
    description: 'Guess cards from 10 different sets',
    category: 'set',
    tier: 'bronze',
    icon: '🎨',
    requirement: 10,
  },
  {
    key: 'set_connoisseur',
    name: 'Set Connoisseur',
    description: 'Guess cards from 25 different sets',
    category: 'set',
    tier: 'silver',
    icon: '🎨',
    requirement: 25,
  },
  {
    key: 'set_master',
    name: 'Set Master',
    description: 'Guess cards from 50 different sets',
    category: 'set',
    tier: 'gold',
    icon: '🎨',
    requirement: 50,
  },
  {
    key: 'complete_collection',
    name: 'Complete Collection',
    description: 'Guess cards from 100 different sets',
    category: 'set',
    tier: 'diamond',
    icon: '🎨',
    requirement: 100,
  },

  // Speed Trophies (4)
  {
    key: 'fast_learner',
    name: 'Quick Thinker',
    description: 'Correctly guess a card in under 5 seconds',
    category: 'speed',
    tier: 'silver',
    icon: '⚡',
    requirement: 5,
  },
  {
    key: 'speed_demon',
    name: 'Speed Demon',
    description: 'Correctly guess a card in under 3 seconds',
    category: 'speed',
    tier: 'gold',
    icon: '⚡',
    requirement: 3,
  },
  {
    key: 'speedrunner',
    name: 'Speedrunner',
    description: 'Correctly guess a card in under 2 seconds',
    category: 'speed',
    tier: 'gold',
    icon: '⚡',
    requirement: 2,
  },
  {
    key: 'reflex_master',
    name: 'Reflex Master',
    description: 'Correctly guess a card in under 1.5 seconds',
    category: 'speed',
    tier: 'diamond',
    icon: '⚡',
    requirement: 1.5,
  },

  // Donation Trophies (4)
  {
    key: 'supporter',
    name: 'Supporter',
    description: 'Make your first donation',
    category: 'donation',
    tier: 'bronze',
    icon: '💝',
    requirement: 1,
  },
  {
    key: 'generous',
    name: 'Generous',
    description: 'Donate $5 or more',
    category: 'donation',
    tier: 'silver',
    icon: '💝',
    requirement: 5,
  },
  {
    key: 'patron',
    name: 'Patron',
    description: 'Donate $20 or more',
    category: 'donation',
    tier: 'gold',
    icon: '💝',
    requirement: 20,
  },
  {
    key: 'benefactor',
    name: 'Benefactor',
    description: 'Donate $50 or more',
    category: 'donation',
    tier: 'diamond',
    icon: '💝',
    requirement: 50,
  },

  // Leaderboard Trophies (5)
  {
    key: 'top_player',
    name: 'Top Player',
    description: 'Reach rank #1 on the leaderboard',
    category: 'leaderboard',
    tier: 'diamond',
    icon: '👑',
    requirement: 1,
  },
  {
    key: 'podium_finish',
    name: 'Podium Finish',
    description: 'Reach top 3 on the leaderboard',
    category: 'leaderboard',
    tier: 'diamond',
    icon: '🥈',
    requirement: 3,
  },
  {
    key: 'top_10',
    name: 'Top 10',
    description: 'Reach top 10 on the leaderboard',
    category: 'leaderboard',
    tier: 'gold',
    icon: '🏅',
    requirement: 10,
  },
  {
    key: 'challenger',
    name: 'Challenger',
    description: 'Reach top 100 on the leaderboard',
    category: 'leaderboard',
    tier: 'silver',
    icon: '🤺',
    requirement: 100,
  },
  {
    key: 'contender',
    name: 'Contender',
    description: 'Reach top 500 on the leaderboard',
    category: 'leaderboard',
    tier: 'bronze',
    icon: '⚔️',
    requirement: 500,
  },
  // Event Trophies (4)
  {
    key: 'quick_draw',
    name: 'Quick Draw',
    description: 'Be the first to guess a card',
    category: 'event',
    tier: 'gold',
    icon: '⚡',
    requirement: 1,
  },
  {
    key: 'good_sport',
    name: 'Good Sport',
    description: 'Give up a round',
    category: 'event',
    tier: 'bronze',
    icon: '🏳️',
    requirement: 1,
  },
  {
    key: 'slow_poke',
    name: 'Slow Poke',
    description: 'Take more than 25 seconds to guess',
    category: 'event',
    tier: 'bronze',
    icon: '🐢',
    requirement: 25,
  },
  {
    key: 'buzzer_beater',
    name: 'Buzzer Beater',
    description: 'Guess at the last second of the round',
    category: 'event',
    tier: 'silver',
    icon: '⏰',
    requirement: 1,
  },

  // Creator Trophies
  {
    key: 'game_creator',
    name: 'Game Creator',
    description: 'Create your first custom game mode',
    category: 'creator',
    tier: 'bronze',
    icon: '🛠️',
    requirement: 1,
  },
  {
    key: 'community_favorite',
    name: 'Community Favorite',
    description: 'Get 10 upvotes on one of your game modes',
    category: 'creator',
    tier: 'silver',
    icon: '❤️',
    requirement: 10,
  },
  {
    key: 'cleanup_crew',
    name: 'Cleanup Crew',
    description: 'Delete one of your custom game modes',
    category: 'creator',
    tier: 'bronze',
    icon: '🧹',
    requirement: 1,
  },
];

async function main() {
  console.log('Seeding trophies...');

  for (const trophy of trophies) {
    await prisma.trophy.upsert({
      where: { key: trophy.key },
      update: trophy,
      create: trophy,
    });
  }

  console.log(`✅ Seeded ${trophies.length} trophies`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
